#!/bin/bash

Start=${1}
FigStride=${2}
End=${3}
SizeBase=${4:-180}
SizeHeight=${5:-60}
Stride=${6:-1}

MidleBase=$((SizeBase/2))
MidleHeight=$((SizeHeight/2))

LocalAddress=$(pwd)



for ii in $(seq ${Start} ${FigStride} ${End})
do

        
    #cut_them_ginzo ${ii} ${ii} ${SizeBase} ${Stride}
    #echo "renderize_pyramid" 0 $((MidleBase-2)) $((MidleBase+2)) $Stride
    
    ginzo2000 0 $((MidleBase-2)) $((MidleBase+2)) $Stride ./director_field_${ii}.csv >./x_plane_${ii}.csv  
    renderize_pyramid_x.py ${SizeBase} ${SizeHeight} ${Stride} x_plane_${ii}.csv
    rm x_plane_${ii}.csv
    
    
    ginzo2000 1 $((MidleBase-2)) $((MidleBase+2))  $Stride ./director_field_${ii}.csv >./y_plane_${ii}.csv  
    renderize_pyramid_y.py ${SizeBase} ${SizeHeight} ${Stride} y_plane_${ii}.csv
    rm y_plane_${ii}.csv
     
    ginzo2000 2 $((MidleHeight-2)) $((MidleHeight+2))  $Stride ./director_field_${ii}.csv >./z_plane_${ii}.csv  
    renderize_pyramid_z.py ${SizeBase} ${SizeHeight} ${Stride} z_plane_${ii}.csv
    rm z_plane_${ii}.csv
    
done
