#!/bin/bash

Start=${1}
FigStride=${2:-1}
End=${3:-${1}}
DirectorSize=${4:-"1e-8"}
FractionOfPoints=${5:-1}

LocalAddress=$(pwd)

for ii in $(seq ${Start} ${FigStride} ${End})
do
    comsol_to_marlics <x_plane_ii_${ii}.csv >x_plane_${ii}.csv
    ${ParaviewDirr}/pvbatch parasol_x.py x_plane_${ii}.csv x_plane_${ii}.png ${DirectorSize} ${FractionOfPoints}
    #rm x_plane_${ii}.csv

    exit
    
    comsol_to_marlics <y_plane_ii_${ii}.csv >y_plane_${ii}.csv
    ${ParaviewDirr}/pvbatch parasol_y.py y_plane_${ii}.csv y_plane_${ii}.png ${DirectorSize} ${FractionOfPoints}
    rm y_plane_${ii}.csv

    ${ParaviewDirr}/pvbatch comsol_to_marlics <z_plane_ii_${ii}.csv >z_plane_${ii}.csv
    parasol_z.py z_plane_${ii}.csv z_plane_${ii}.png ${DirectorSize} ${FractionOfPoints}
    rm z_plane_${ii}.csv

done
